language: python
python:
  - '3.6'
install:
  - pip install --upgrade pip
  - pip install --progress-bar off . '.[dev]'

script:
  - pytest
  - pycodestyle --max-line-length=80 --count --statistics .
  - mypy scraper/ --disallow-incomplete-defs
